---
jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: maven-resource
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-rc
    params:
      build: maven-resource
      tag: version/version
      tag_as_latest: true
  - put: tracker
    params:
      repos:
        - maven-resource

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: maven-resource-image-rc
      passed: [build]
      params: {save: true}
    - get: version
      passed: [build]
      params: {bump: final}
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-final
    params:
      load: maven-resource-image-rc
      tag: version/version
      tag_as_latest: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

resources:
- name: maven-resource
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}
    private_key: {{git-private-key}}
    ignore_paths:
    - LICENSE
    - NOTICE.md
    - pipeline.yml
    - README.md

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: version
    private_key: {{git-private-key}}

- name: maven-resource-image-rc
  type: docker-image
  source:
    repository: {{docker-repository-rc}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: maven-resource-image-final
  type: docker-image
  source:
    repository: {{docker-repository-final}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}
