---
jobs:
- name: build
  plan:
  - get: maven-resource
    trigger: true
  - put: maven-resource-image
    params: {build: maven-resource}
  - put: tracker

resources:
- name: maven-resource
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}
    private_key: {{github-private-key}}

- name: maven-resource-image
  type: docker-image
  source:
    repository: {{docker-repository}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}
